version: "3.8"
services:
  client:
    image: node-v14
    environment:
      - PORT=${PORT}
      - APP_DIR=/client
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:${APP_DIR}
    env_file:
      - .env
    command: "npm start --prefix client"
